from pathlib import Path
from rich.console import Console
from rich.panel import Panel

console = Console()

def create_project(project_name: str):
    project_name = project_name.lower()
    
    if project_name != "fastapi":
        error_panel = Panel(
            "[red bold]❌ Ошибка: поддерживается только 'fastapi'![/red bold]\n\n"
            "[yellow]Доступные проекты:[/yellow]\n"
            "[bold]fastapi[/bold] - Современный веб-фреймворк 🚀",
            title="🚫 Неподдерживаемый проект",
            border_style="red"
        )
        console.print(error_panel)
        return

    cwd = Path.cwd()
    
    if any(cwd.iterdir()):
        base_path = cwd / "fastapi_project"
    else:
        base_path = cwd / "fastapi_project"

    console.print(f"\n[bold cyan]🔨 🚀 Создаю FastAPI проект в папке 'fastapi_project'...[/bold cyan]\n")
    
    folders = [
        "backend",
        "backend/docs",
        "backend/app",
        "backend/app/database",
        "backend/app/schema", 
        "backend/app/routers",
        "backend/app/broker",
        "backend/app/functions"
    ]

    for i, folder in enumerate(folders, 1):
        folder_path = base_path / folder
        folder_path.mkdir(parents=True, exist_ok=True)
        console.print(f"[dim]  {i:2d}/{len(folders)}[/dim] 📁 [bold green]Создана папка:[/bold green] {folder}")

    init_files = [
        "backend/__init__.py",
        "backend/app/database/__init__.py",
        "backend/app/schema/__init__.py",
        "backend/app/routers/__init__.py",
        "backend/app/broker/__init__.py",
        "backend/app/functions/__init__.py"
    ]

    for i, file_path in enumerate(init_files, 1):
        full_path = base_path / file_path
        full_path.touch(exist_ok=True)
        console.print(f"[dim]  {i:2d}/{len(init_files)}[/dim] 📄 [bold blue]Создан файл:[/bold blue] {file_path}")

    main_files = [
        ("backend/app/main.py", "# FastAPI main application\nfrom fastapi import FastAPI\n\napp = FastAPI()\n"),
        ("backend/docs/README.md", "# FastAPI Project\n\nGenerated by GRAM CLI 🚀\n")
    ]

    for file_path, content in main_files:
        full_path = base_path / file_path
        full_path.write_text(content, encoding="utf-8")
        console.print(f"[dim]      [/dim] ✨ [bold yellow]Основной файл:[/bold yellow] {file_path}")

    success_panel = Panel(
        f"[bold bright_green]🎉 FastAPI проект успешно создан![/bold bright_green]\n"
        f"[cyan]📍 Расположение:[/cyan] [yellow]{base_path}[/yellow]\n"
        f"[cyan]🏗️  Создано:[/cyan] [green]{len(folders)} папок[/green], [blue]{len(init_files)} файлов[/blue]",
        title="🚀 Проект готов!",
        border_style="bright_green"
    )
    console.print("\n")
    console.print(success_panel)
    console.print(f"\n[dim]💡 Подсказка: Проект создан в папке fastapi_project/backend. Перейдите туда и начните разработку![/dim]\n")